# Generated by Django 2.0.4 on 2018-04-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pontoturistico_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='descricao',
            field=models.TextField(verbose_name='descricao'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='nome',
            field=models.CharField(max_length=150, verbose_name='nome'),
        ),
    ]
