# Generated by Django 2.0.4 on 2018-04-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180426_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
